# site properties and page defaults
title: Ambient Intelligence Lab
subtitle: 
description: We envision a future where our environments intuitively adapt in real-time to augment human abilities through Ambient Intelligence (AmI).
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@Ambient-Intelligence-Lab-UMich-EECS.com
  orcid: 0000-0001-8713-9213
  google-scholar: YZWCK4gAAAAJ
  github: https://github.com/Ambient-Intelligence-Lab-UMich-EECS
  twitter: Ambient-Intelligence-Lab-UMich-EECS
  youtube: Ambient-Intelligence-Lab-UMich-EECS

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
